export const sections = [
  { id:'keybinds', label:'Keybinds', icon:'keys', desc:'Hold to zoom. Each slot accepts a mouse side-button or a key. Right-click a binding to clear it.', rows: [
    { key:'__zoomIn',   type:'keybind', label:'Zoom in',  desc:'Hold to magnify',  buttonKey:'zoomInButton',  vkKey:'zoomInVk',  modsKey:'zoomInMods' },
    { key:'__zoomOut',  type:'keybind', label:'Zoom out', desc:'Hold to zoom back', buttonKey:'zoomOutButton', vkKey:'zoomOutVk', modsKey:'zoomOutMods' },
    { key:'altKeybinds', type:'toggle', label:'Enable alternate keybinds', desc:'Adds an optional second binding (side-button or key) per direction.', def:0 },
    { key:'__zoomIn2',  type:'keybind', label:'Zoom in (alternate)',  desc:'Optional side-button or key', buttonKey:'zoomInButton2',  vkKey:'zoomInVk2',  modsKey:'zoomInMods2',  requires:'altKeybinds' },
    { key:'__zoomOut2', type:'keybind', label:'Zoom out (alternate)', desc:'Optional side-button or key', buttonKey:'zoomOutButton2', vkKey:'zoomOutVk2', modsKey:'zoomOutMods2', requires:'altKeybinds' },
  ]},
  { id:'zoom', label:'Zoom', icon:'zoom', desc:'How magnification grows while you hold the zoom button.', rows: [
    { key:'zoomInSpeed',  type:'slider', label:'Zoom-in speed',  desc:'Multiplier (1.0 = default).', min:0.25, max:4, step:0.05, def:1.0 },
    { key:'zoomOutSpeed', type:'slider', label:'Zoom-out speed', desc:'Multiplier (1.0 = default).', min:0.25, max:4, step:0.05, def:1.0 },
    { key:'maxLevel',     type:'slider', label:'Max zoom',       desc:'How far you can zoom.', min:2, max:50, step:1, def:12.0 },
    { key:'smoothZoom',   type:'toggle', label:'Smooth zoom',    desc:'Zoom-in eases up to your speed.', def:0, advanced:true },
    { key:'smoothZoomAccel', type:'slider', label:'Smooth ease-in depth', desc:'Higher = slower start.', min:1, max:8, step:0.5, def:3.0, dependsOn:'smoothZoom', advanced:true },
    { key:'smoothZoomRamp',  type:'slider', label:'Smooth ramp (s)', desc:'Seconds to reach full speed.', min:0.1, max:3, step:0.1, def:0.6, dependsOn:'smoothZoom', advanced:true },
    { key:'quickZoomHotkeyMode', type:'segmented', label:'Quick zoom', desc:'Toggle 0% and your last level (above 200%). Choose the trigger.', seg:['Modifier','Hotkey'], def:0 },
    { key:'quickZoomModifier', type:'select', label:'Modifier key', desc:'Hold this and tap a zoom key to toggle. None = off.', options:['None','Ctrl','Alt','Shift'], def:'Ctrl', requiresNot:'quickZoomHotkeyMode' },
    { key:'__quickZoom', type:'keybind', label:'Quick-zoom hotkey', desc:'Press to toggle quick zoom. Right-click to clear (off). Default F1.', vkKey:'quickZoomVk', modsKey:'quickZoomMods', requires:'quickZoomHotkeyMode' },
  ]},
  { id:'cursor', label:'Cursor', icon:'cursor', desc:'Pointer movement and visibility while zoomed.', rows: [
    { key:'cursorSensitivity', type:'slider', label:'Cursor speed', desc:'Pan speed multiplier (1.0 = match your mouse).', min:0.25, max:4, step:0.05, def:1.0, advanced:true },
    { key:'cursorSmoothing',   type:'slider', label:'Cursor inertia smoothing', desc:'0 = off, higher = smoother.', min:0, max:0.95, step:0.05, def:0.4 },
    { key:'cursorScaleWithZoom', type:'toggle', label:'Scale cursor with zoom', def:1, advanced:true },
    { key:'cursorVisibility', type:'select', label:'Cursor visibility', options:['auto','always','never'], def:'auto', advanced:true },
    { key:'__hideCursor', type:'keybind', label:'Hide cursor (hotkey)', desc:'Press to instantly toggle the magnified cursor. Does not reset zoom.', vkKey:'hideCursorVk', modsKey:'hideCursorMods' },
    { key:'__cursorLock', type:'keybind', label:'Inspect mode', desc:'Freeze the cursor (keeps a hover or tooltip alive) and free-look around with a crosshair that pans the view, at any zoom. Press to set, right-click to clear.', vkKey:'cursorLockVk' },
  ]},
  { id:'display', label:'Display', icon:'display', desc:'Image quality of the magnified view.', rows: [
    { key:'model', type:'select', label:'Magnifier model',
      desc:'Render = high-fidelity GPU overlay (covers the shell). Magnify = drives the native Windows Magnifier; use it for DRM video (Netflix) that shows black in Render. Restart to switch.',
      options:['render','magnify'], def:'render' },
    { key:'__swapModel', type:'keybind', label:'Swap model hotkey',
      desc:'Press to switch between Render and Magnify (restarts Wind). Right-click to clear.',
      vkKey:'swapModelVk' },
    { key:'magnifyStep', type:'select', label:'Zoom step',
      desc:'Windows Magnifier zoom increment, percent per step. Lower = smoother and slower. Applies live.',
      options:['5','10','25','50','100'], def:'50', showIf:{ key:'model', eq:'magnify' } },
    { key:'bilinear',    type:'toggle', label:'Smooth scaling', desc:'Bilinear vs crisp pixels.', def:1, advanced:true, showIf:{ key:'model', eq:'render' } },
    { key:'sharpness',   type:'slider', label:'Sharpness', desc:'Crisps the magnified image (0 = off).', min:0, max:1, step:0.05, def:0.0, advanced:true, showIf:{ key:'model', eq:'render' } },
    { key:'brightness',  type:'slider', label:'Brightness', min:0.5, max:1.5, step:0.05, def:1.0, advanced:true, showIf:{ key:'model', eq:'render' } },
    { key:'hdrTonemap',  type:'toggle', label:'HDR tonemap', desc:'HDR10 to SDR when HDR is on.', def:1, advanced:true, showIf:{ key:'model', eq:'render' } },
    { key:'multiMonitor',type:'toggle', label:'Follow cursor monitor', def:0 },
    { key:'outline',          type:'toggle', label:'Edge outline',
      desc:'Show an outline around the screen while zoomed.', def:0, showIf:{ key:'model', eq:'render' } },
    { key:'outlineThickness', type:'slider', label:'Outline thickness',
      desc:'Width in pixels.', min:1, max:40, step:1, def:4, dependsOn:'outline', showIf:{ key:'model', eq:'render' } },
    { key:'outlineColor',     type:'color',  label:'Outline color',
      def:'#5b5bd6', dependsOn:'outline', showIf:{ key:'model', eq:'render' } },
    { key:'outlineLowZoomOnly', type:'toggle', label:'Only at low zoom',
      desc:'Hide the outline once you zoom past the cutoff.', def:0, dependsOn:'outline', showIf:{ key:'model', eq:'render' } },
    { key:'outlineLowZoomMax',  type:'slider', label:'Low-zoom cutoff',
      desc:'Show only at or below this zoom (2 = 200%).', min:1.25, max:2, step:0.05, def:2,
      dependsOn:'outlineLowZoomOnly', showIf:{ key:'model', eq:'render' } },
    { key:'outlineIdleHide',    type:'toggle', label:'Hide when idle',
      desc:'Fade the outline out when the mouse is still.', def:0, dependsOn:'outline', showIf:{ key:'model', eq:'render' } },
    { key:'outlineIdleSeconds', type:'slider', label:'Idle timeout (s)',
      desc:'Seconds of no movement before it fades.', min:1, max:30, step:1, def:7,
      dependsOn:'outlineIdleHide', showIf:{ key:'model', eq:'render' } },
  ]},
  { id:'about', label:'About', icon:'about', desc:'', rows: [
    { key:'diagnostics', type:'toggle', label:'Frametime logging', desc:'Write timing to a log file.', def:0 },
    { key:'showAdvanced', type:'toggle', label:'Show advanced settings', desc:'Reveal advanced options.', def:0 },
    { key:'__about', type:'about' },
  ]},
];
