// The tray flyout's theme table (#318): lookup by uiPalette id, the Wind grey fallback, one row per Settings
// palette in the same order, and the invariants the painter relies on. Pure; flyout_palettes.h is generated by
// ui/tools/gen-flyout-palettes.cjs from the same mockup palettes as the Settings themes.
#include "../third_party/doctest.h"
#include "../src/tray_app/flyout_palettes.h"
#include "../src/config.h"
#include <string>
using namespace wind;
using namespace wind::Flyout;

TEST_CASE("flyout palettes: one row per Settings palette, same ids in the same order") {
    int n = 0;
    const char* const* ids = UiPaletteIds(n);
    REQUIRE(n == kPaletteCount);
    for (int i = 0; i < n; ++i) CHECK(std::string(kPalettes[i].id) == ids[i]);
}

TEST_CASE("flyout palettes: lookup by id") {
    CHECK(PaletteIndex("grey") == 0);
    CHECK(PaletteIndex("ember") == 1);
    CHECK(PaletteIndex("cyber") == 2);
    CHECK(PaletteIndex("mono") == 3);
    CHECK(PaletteIndex("slate") == 4);
    CHECK(PaletteIndex("carbon") == 5);
    CHECK(PaletteIndex("hicon") == 6);
    CHECK(PaletteIndex("ocean") == 7);
    CHECK(std::string(FindPalette("ocean").id) == "ocean");
}

TEST_CASE("flyout palettes: unknown, empty or wrong-case ids fall back to Wind grey") {
    CHECK(PaletteIndex("") == 0);
    CHECK(PaletteIndex("nope") == 0);
    CHECK(PaletteIndex("Ember") == 0);      // ids are exact, like the Settings app's normalizePalette
    CHECK(PaletteIndex("b1_mono") == 0);    // mockup ids are not app ids
    CHECK(std::string(FindPalette("zzz").id) == "grey");
    CHECK(&PaletteAt(-1) == &kPalettes[0]);
    CHECK(&PaletteAt(kPaletteCount) == &kPalettes[0]);
    CHECK(&PaletteFor(99, true) == &kPalettes[0].dark);
    CHECK(&PaletteFor(2, false) == &kPalettes[2].light);
}

TEST_CASE("flyout palettes: Wind grey keeps the look the flyout already had") {
    const FlyoutPalette& g = kPalettes[0];
    CHECK(g.dark.menu == 0x000000);
    CHECK(g.dark.fill == 0x2fbfa5);
    CHECK(g.dark.on == 0x1f5650);
    CHECK(g.light.menu == 0xffffff);
    CHECK(g.light.on == 0xbfe2db);
    CHECK(g.light.legacyLight == 1);
    CHECK(g.dark.tintA == 0.f);
}

TEST_CASE("flyout palettes: radii are sharp for cyber, carbon and hicon, soft elsewhere") {
    for (const char* id : { "cyber", "carbon", "hicon" }) {
        const FlyoutPalette& p = FindPalette(id);
        CHECK(p.rc == 4);
        CHECK(p.rk == 3);
        CHECK(p.rs == 2);
        CHECK(ListRadiusFor(p) == 4.f);
    }
    for (const char* id : { "grey", "ember", "mono", "slate", "ocean" }) {
        const FlyoutPalette& p = FindPalette(id);
        CHECK(p.rc == 10);
        CHECK(p.rk == 8);
        CHECK(p.rs == 6);
        CHECK(ListRadiusFor(p) == 8.f);
    }
}

TEST_CASE("flyout palettes: Cyberpunk dark has solid yellow on-segments with black icons") {
    const PaletteMode& d = FindPalette("cyber").dark;
    CHECK(d.on == 0xfcee0a);
    CHECK(d.onh == 0xfcee0a);
    CHECK(d.onic == 0x000000);
}

TEST_CASE("flyout palettes: every mode is fully specified and on-state differs from off") {
    for (int i = 0; i < kPaletteCount; ++i) {
        for (bool dark : { true, false }) {
            const PaletteMode& m = PaletteFor(i, dark);
            INFO(kPalettes[i].id << (dark ? " dark" : " light"));
            CHECK(m.menu <= 0xffffff);
            CHECK(m.on != m.off);
            CHECK(m.fg != m.menu);
            CHECK(m.aurora > 0.f);
            CHECK(m.aurora <= 1.f);
            CHECK(m.tintA >= 0.f);
            CHECK(m.tintA <= 1.f);
        }
    }
}
