// The tray flyout's theme table (#318): lookup by uiPalette id, the Wind grey fallback, one row per Settings
// palette in the same order, and the invariants the painter relies on. Pure; flyout_palettes.h is generated by
// ui/tools/gen-flyout-palettes.cjs from the same mockup palettes as the Settings themes.
#include "../third_party/doctest.h"
#include "../src/tray_app/flyout_palettes.h"
#include "../src/config.h"
#include <string>
using namespace wind;
using namespace wind::Flyout;

TEST_CASE("flyout palettes: one row per Settings palette, same ids in the same order") {
    int n = 0;
    const char* const* ids = UiPaletteIds(n);
    REQUIRE(n == kPaletteCount);
    for (int i = 0; i < n; ++i) CHECK(std::string(kPalettes[i].id) == ids[i]);
}

TEST_CASE("flyout palettes: lookup by id") {
    CHECK(PaletteIndex("grey") == 0);
    CHECK(PaletteIndex("ember") == 1);
    CHECK(PaletteIndex("ocean") == 2);
    CHECK(PaletteIndex("hicon") == 3);      // High contrast is always last
    CHECK(kPaletteCount == 4);
    CHECK(std::string(FindPalette("ocean").id) == "ocean");
}

TEST_CASE("flyout palettes: unknown, empty or wrong-case ids fall back to Wind grey") {
    CHECK(PaletteIndex("") == 0);
    CHECK(PaletteIndex("nope") == 0);
    CHECK(PaletteIndex("Ember") == 0);      // ids are exact, like the Settings app's normalizePalette
    CHECK(PaletteIndex("b1_hicon") == 0);   // mockup ids are not app ids
    for (const char* gone : { "cyber", "mono", "slate", "carbon" }) CHECK(PaletteIndex(gone) == 0);   // removed themes read as grey
    CHECK(std::string(FindPalette("zzz").id) == "grey");
    CHECK(&PaletteAt(-1) == &kPalettes[0]);
    CHECK(&PaletteAt(kPaletteCount) == &kPalettes[0]);
    CHECK(&PaletteFor(99) == &kPalettes[0].dark);
    CHECK(&PaletteFor(2) == &kPalettes[2].dark);
}

TEST_CASE("flyout palettes: Wind grey keeps the look the flyout already had") {
    const FlyoutPalette& g = kPalettes[0];
    CHECK(g.dark.menu == 0x000000);
    CHECK(g.dark.fill == 0x2fbfa5);
    CHECK(g.dark.on == 0x2fbfa5);     // solid teal ON segments with a near-black icon (#329)
    CHECK(g.dark.onic == 0x04201b);
    CHECK(g.dark.tintA == 0.f);
}

TEST_CASE("flyout palettes: radii are sharp for hicon, soft elsewhere") {
    for (const char* id : { "hicon" }) {
        const FlyoutPalette& p = FindPalette(id);
        CHECK(p.rc == 4);
        CHECK(p.rk == 3);
        CHECK(p.rs == 2);
        CHECK(ListRadiusFor(p) == 4.f);
    }
    for (const char* id : { "grey", "ember", "ocean" }) {
        const FlyoutPalette& p = FindPalette(id);
        CHECK(p.rc == 10);
        CHECK(p.rk == 8);
        CHECK(p.rs == 6);
        CHECK(ListRadiusFor(p) == 8.f);
    }
}

TEST_CASE("flyout palettes: High contrast dark is white on black, ON segments solid white with a black icon (#329)") {
    const PaletteMode& d = FindPalette("hicon").dark;
    CHECK(d.menu == 0x000000);
    CHECK(d.fg == 0xffffff);
    CHECK(d.on == 0xffffff);
    CHECK(d.onic == 0x000000);
}

TEST_CASE("flyout palettes: every palette is fully specified, dark, and on-state differs from off") {
    for (int i = 0; i < kPaletteCount; ++i) {
        {
            const PaletteMode& m = PaletteFor(i);
            INFO(kPalettes[i].id);
            // Dark only since #324: the window colour is near black and the text is lighter than it.
            CHECK(((m.menu >> 16) & 0xff) < 0x30);
            CHECK(((m.menu >> 8) & 0xff) < 0x30);
            CHECK((m.menu & 0xff) < 0x30);
            CHECK(m.fg > m.menu);
            CHECK(m.menu <= 0xffffff);
            CHECK(m.on != m.off);
            CHECK(m.fg != m.menu);
            CHECK(m.aurora > 0.f);
            CHECK(m.aurora <= 1.f);
            CHECK(m.tintA >= 0.f);
            CHECK(m.tintA <= 1.f);
        }
    }
}
