// GENERATED by ui/tools/gen-themes.cjs. The built-in themes in picker order; ids match the core's kUiPalettes.
export const themes = [
  { id: 'grey', label: 'Wind grey' },
  { id: 'ember', label: 'Ember' },
  { id: 'ocean', label: 'Deep ocean' },
  { id: 'hicon', label: 'High contrast' },
];
export const themeIds = themes.map((t) => t.id);
export const normalizePalette = (v) => (themeIds.includes(v) ? v : 'grey');
