#pragma once
// GENERATED by ui/tools/gen-flyout-palettes.cjs from the mockup palettes (palettes08/-b1/-b2.cjs + tray08.css). Do not edit by hand.
// The tray flyout's 4 themes (dark only), the same ids and values as the Settings themes (ui/src/design/themes.css), plus the
// tray tokens tray08.css derives (toggle off/on fills, on icon, on-segment overrides).
// Pure data: no windows.h. Colours are 0xRRGGBB; the float fields are alphas and flags.
#include <string>

namespace wind { namespace Flyout {

struct PaletteMode {
    unsigned menu, card, menub, fg, fg2, fg3, rule, hl, glyph, spark, fill, fillline, lift, scrim, band, track,
             off, offh, offic, onic, on, onh, onb, segline, focus, tint,
             ring;   // the 1 px outline of the toggle bar and the dropdown (Settings --chipb)
    float filllineA;    // 1 = a 1 px ring around the slider fill (High contrast), 0 = none
    float scrimA;       // the header scrim, over menu
    float onbA;         // alpha of the open dropdown ring (onb)
    float aurora;       // header image opacity
    float tintA;        // colour-blend tint over the header image (0 = none)
};

struct FlyoutPalette {
    const char* id;
    int rc, rk, rs;     // window, control and small radii in DIPs (sharp for hicon)
    PaletteMode dark;   // the only mode: the flyout is always dark (#324)
};

inline constexpr int kPaletteCount = 4;
inline const FlyoutPalette kPalettes[kPaletteCount] = {
    { "grey", 10, 8, 6,
      { 0x000000, 0x121212, 0x191919, 0xf2f2f2, 0xd0d0d0, 0xb4b6ba, 0x18191a, 0x2d2d2d, 0xb0b0b0, 0x2fbfa5, 0x2fbfa5, 0x000000, 0x0b0b0b, 0x000000, 0x0a0a0a, 0x3d3d3d, 0x0e0e0e, 0x1c1c1c, 0xc8cad0, 0x04201b, 0x2fbfa5, 0x45cbb3, 0x2fbfa5, 0x222222, 0xf2f2f2, 0x000000, 0x222222,
      0.f, 0.55f, 0.4f, 0.62f, 0.f } },
    { "ember", 10, 8, 6,
      { 0x0c0908, 0x130e0b, 0x261d17, 0xf5eee7, 0xd8cbbf, 0xa39382, 0x1f1611, 0x1d1612, 0xb9a898, 0xe48a45, 0xe48a45, 0x000000, 0x130e0b, 0x0c0908, 0x130e0b, 0x3a2e25, 0x18120e, 0x251f1b, 0xb9a898, 0x1c0f06, 0xe48a45, 0xe69658, 0xe48a45, 0x3a2c23, 0xe48a45, 0xff8a3d, 0x3a2c23,
      0.f, 0.62f, 0.4f, 0.68f, 0.8f } },
    { "ocean", 10, 8, 6,
      { 0x0c1117, 0x121821, 0x1f2938, 0xf1f2f4, 0xc6cbd2, 0x9aa2ac, 0x19212e, 0x19222e, 0xb0b6bf, 0x5aaaf5, 0x5aaaf5, 0x000000, 0x121821, 0x0c1117, 0x121821, 0x2d3a4e, 0x161e29, 0x232b35, 0xb0b6bf, 0x061018, 0x5aaaf5, 0x6cb3f5, 0x5aaaf5, 0x263345, 0x5aaaf5, 0x5aaaf5, 0x263345,
      0.f, 0.62f, 0.4f, 0.68f, 0.7f } },
    { "hicon", 4, 3, 2,
      { 0x000000, 0x000000, 0xbdbdbd, 0xffffff, 0xffffff, 0xe0e0e0, 0x9a9a9a, 0x262626, 0xffffff, 0xffffff, 0xffffff, 0x000000, 0x000000, 0x000000, 0x000000, 0x4a4a4a, 0x000000, 0x0f0f0f, 0xffffff, 0x000000, 0xffffff, 0xffffff, 0xffffff, 0xbdbdbd, 0xffffff, 0x000000, 0xbdbdbd,
      0.f, 0.62f, 0.4f, 0.408f, 0.f } },
};

// The palette index for a uiPalette value; anything unknown or empty is Wind grey (index 0).
inline int PaletteIndex(const std::string& id) {
    for (int i = 0; i < kPaletteCount; ++i) if (id == kPalettes[i].id) return i;
    return 0;
}
inline const FlyoutPalette& FindPalette(const std::string& id) { return kPalettes[PaletteIndex(id)]; }
inline const PaletteMode& PaletteFor(int index) { return kPalettes[index >= 0 && index < kPaletteCount ? index : 0].dark; }
inline const FlyoutPalette& PaletteAt(int index) { return kPalettes[index >= 0 && index < kPaletteCount ? index : 0]; }
// The list popup is 2 DIPs tighter than the window when the window is soft (10 -> 8), the same radius when sharp.
inline float ListRadiusFor(const FlyoutPalette& p) { return p.rc >= 10 ? (float)(p.rc - 2) : (float)p.rc; }

}}  // namespace wind::Flyout
