#pragma once
// GENERATED by ui/tools/gen-flyout-palettes.cjs from the mockup palettes (palettes08/-b1/-b2.cjs + tray08.css). Do not edit by hand.
// The tray flyout's 4 themes x 2 modes, the same ids and values as the Settings themes (ui/src/design/themes.css), plus the
// tray tokens tray08.css derives (toggle off/on fills, on icon, on-segment overrides).
// Pure data: no windows.h. Colours are 0xRRGGBB; the float fields are alphas and flags.
#include <string>

namespace wind { namespace Flyout {

struct PaletteMode {
    unsigned menu, card, menub, fg, fg2, fg3, rule, hl, glyph, spark, fill, fillline, lift, scrim, band, track,
             off, offh, offic, onic, on, onh, onb, segline, focus, tint,
             ring;   // the 1 px outline of the toggle bar and the dropdown (Settings --chipb)
    float filllineA;    // 1 = a 1 px ring around the slider fill (High contrast), 0 = none
    float scrimA;       // the header scrim, over menu
    float onbA;         // alpha of the open dropdown ring (onb)
    float aurora;       // header image opacity
    float tintA;        // colour-blend tint over the header image (0 = none)
    int invert;         // the light header image is inverted
    int legacyLight;    // Wind grey light: the full invert/hue-rotate/saturate/contrast chain the j01 reference uses
};

struct FlyoutPalette {
    const char* id;
    int rc, rk, rs;     // window, control and small radii in DIPs (sharp for hicon)
    PaletteMode dark, light;
};

inline constexpr int kPaletteCount = 4;
inline const FlyoutPalette kPalettes[kPaletteCount] = {
    { "grey", 10, 8, 6,
      { 0x000000, 0x121212, 0x191919, 0xf2f2f2, 0xd0d0d0, 0xb4b6ba, 0x18191a, 0x2d2d2d, 0xb0b0b0, 0x2fbfa5, 0x2fbfa5, 0x000000, 0x0b0b0b, 0x000000, 0x0a0a0a, 0x3d3d3d, 0x0e0e0e, 0x1c1c1c, 0xc8cad0, 0xa9ece0, 0x1f5650, 0x266560, 0x2fbfa5, 0x222222, 0xf2f2f2, 0x000000, 0x222222,
      0.f, 0.55f, 0.4f, 0.62f, 0.f, 0, 0 },
      { 0xffffff, 0xffffff, 0xe3e4e4, 0x0a0a0a, 0x2e2e2e, 0x45484d, 0xd7d9dd, 0xececec, 0x555555, 0x087a67, 0x087a67, 0x000000, 0xf6f7f8, 0xffffff, 0xf1f2f4, 0xd0d3d6, 0xf7f7f7, 0xe9e9e9, 0x3d4147, 0x0a5a4d, 0xbfe2db, 0xb2d9d1, 0x087a67, 0xdcdcdc, 0x0a0a0a, 0x000000, 0xdcdcdc,
      0.f, 0.78f, 0.4f, 0.85f, 0.f, 0, 1 } },
    { "ember", 10, 8, 6,
      { 0x0c0908, 0x130e0b, 0x261d17, 0xf5eee7, 0xd8cbbf, 0xa39382, 0x1f1611, 0x1d1612, 0xb9a898, 0xe48a45, 0xe48a45, 0x000000, 0x130e0b, 0x0c0908, 0x130e0b, 0x3a2e25, 0x18120e, 0x251f1b, 0xb9a898, 0xe9a876, 0x704c31, 0x7e5433, 0xe48a45, 0x3a2c23, 0xe48a45, 0xff8a3d, 0x3a2c23,
      0.f, 0.62f, 0.4f, 0.68f, 0.8f, 0, 0 },
      { 0xf7f2ed, 0xfffdfb, 0xd9ccc1, 0x261a12, 0x4b3b2f, 0x6c5a4b, 0xe3d9ce, 0xefe6dd, 0x5f4d40, 0xb0540d, 0xb9590f, 0x000000, 0xfffdfb, 0xf7f2ed, 0xfffdfb, 0xe0d2c4, 0xfaf5f0, 0xede8e3, 0x5f4d40, 0x87430f, 0xd5b194, 0xd2a683, 0xb9590f, 0xcbbbad, 0xb0540d, 0xe07a2f, 0xcbbbad,
      0.f, 0.62f, 0.4f, 0.748f, 0.55f, 1, 0 } },
    { "ocean", 10, 8, 6,
      { 0x0c1117, 0x121821, 0x1f2938, 0xf1f2f4, 0xc6cbd2, 0x9aa2ac, 0x19212e, 0x19222e, 0xb0b6bf, 0x5aaaf5, 0x5aaaf5, 0x000000, 0x121821, 0x0c1117, 0x121821, 0x2d3a4e, 0x161e29, 0x232b35, 0xb0b6bf, 0x87c0f5, 0x3d5d7d, 0x41678c, 0x5aaaf5, 0x263345, 0x5aaaf5, 0x5aaaf5, 0x263345,
      0.f, 0.62f, 0.4f, 0.68f, 0.7f, 0, 0 },
      { 0xeff3f8, 0xfcfcfd, 0xbbc8d7, 0x11171d, 0x323c48, 0x53606e, 0xd2ddeb, 0xe1e9f2, 0x485360, 0x1262b8, 0x1262b8, 0x000000, 0xfcfcfd, 0xeff3f8, 0xfcfcfd, 0xc1d0e1, 0xf4f7fa, 0xe6eaed, 0x485360, 0x124c89, 0x96b3d3, 0x85a9d0, 0x1262b8, 0xa4b6ca, 0x1262b8, 0x1262b8, 0xa4b6ca,
      0.f, 0.62f, 0.4f, 0.748f, 0.55f, 1, 0 } },
    { "hicon", 4, 3, 2,
      { 0x000000, 0x000000, 0xbdbdbd, 0xffffff, 0xffffff, 0xe0e0e0, 0x9a9a9a, 0x262626, 0xffffff, 0xffffff, 0xffffff, 0x000000, 0x000000, 0x000000, 0x000000, 0x4a4a4a, 0x000000, 0x0f0f0f, 0xffffff, 0xffffff, 0x707070, 0x828282, 0xffffff, 0xbdbdbd, 0xffffff, 0x000000, 0xbdbdbd,
      0.f, 0.62f, 0.4f, 0.408f, 0.f, 0, 0 },
      { 0xffffff, 0xffffff, 0x2a2a2a, 0x000000, 0x000000, 0x1f1f1f, 0x3c3c3c, 0xe6e6e6, 0x000000, 0x000000, 0x000000, 0x000000, 0xffffff, 0xffffff, 0xffffff, 0xb8b8b8, 0xffffff, 0xf0f0f0, 0x000000, 0x000000, 0x8f8f8f, 0x7d7d7d, 0x000000, 0x2a2a2a, 0x000000, 0x000000, 0x2a2a2a,
      0.f, 0.62f, 0.4f, 0.51f, 0.f, 1, 0 } },
};

// The palette index for a uiPalette value; anything unknown or empty is Wind grey (index 0).
inline int PaletteIndex(const std::string& id) {
    for (int i = 0; i < kPaletteCount; ++i) if (id == kPalettes[i].id) return i;
    return 0;
}
inline const FlyoutPalette& FindPalette(const std::string& id) { return kPalettes[PaletteIndex(id)]; }
inline const PaletteMode& PaletteFor(int index, bool dark) {
    const FlyoutPalette& p = kPalettes[index >= 0 && index < kPaletteCount ? index : 0];
    return dark ? p.dark : p.light;
}
inline const FlyoutPalette& PaletteAt(int index) { return kPalettes[index >= 0 && index < kPaletteCount ? index : 0]; }
// The list popup is 2 DIPs tighter than the window when the window is soft (10 -> 8), the same radius when sharp.
inline float ListRadiusFor(const FlyoutPalette& p) { return p.rc >= 10 ? (float)(p.rc - 2) : (float)p.rc; }

}}  // namespace wind::Flyout
