// Generates ui/src/design/themes.css and ui/src/design/themes.js from the mockup palette files
// (wind-settings-mockups/ia/palettes08.cjs, palettes-b1.cjs, palettes-b2.cjs, the owner's final pick of 2026-10-02).
//
//   node tools/gen-themes.cjs [mockup-ia-dir]
//
// The mockup token names are mapped onto the app's design tokens (src/design/tokens.css):
//   bg side line line2 rowline hover card chip chipb cardb fg fg2 fg3 glyph track fill pill pillb shadow  -> same name
//   hb -> --outline (hover border)   pbg/pfg -> --accent/--onaccent (primary button)   sel -> --hlGrey
//   knob -> --ctl   bnbg/bnop -> --band/--bandimg-op   rk/rs -> --rad/--srad
// New tokens (tokens.css gives each a default): sel selfg onfill fillline focus hover2 danger dangerbg
// dangerbtn dangerbtnfg scrim bnfilter bntint bntop rc rp rsw rkn.
// Wind grey takes the app's own tokens.css values for every token the app already had, so
// today's look is exactly preserved; every other theme comes from the mockup palettes.
// Palette ids in the app: grey ember ocean hicon (the core's kUiPalettes, src/config.cpp). Four themes only (owner decision 2026-10-02).
// Dark only since 0.20.0 (#324): the mockup palettes' light halves are not read.
const fs = require('fs');
const path = require('path');

const iaDir = process.argv[2] || 'C:/Users/Admin/Documents/Claude/wind-settings-mockups/ia';
const all = Object.assign({}, require(path.join(iaDir, 'palettes08.cjs')),
  require(path.join(iaDir, 'palettes-b1.cjs')), require(path.join(iaDir, 'palettes-b2.cjs')));
// app id -> mockup id, in picker order
const ORDER = [['grey', 'grey'], ['ember', 'ember'], ['ocean', 'b2_ocean'], ['hicon', 'b1_hicon']];

// --- today's tokens (src/design/tokens.css, the first .wnd block) ---
const tokensCss = fs.readFileSync(path.join(__dirname, '../src/design/tokens.css'), 'utf8');
const start = tokensCss.indexOf('.wnd {');
const block = tokensCss.slice(start + 6, tokensCss.indexOf('\n}', start));
const pairs = (text) => {
  const o = {};
  for (const m of text.replace(/\/\*[\s\S]*?\*\//g, '').matchAll(/--([A-Za-z0-9-]+):\s*([^;]+);/g)) o[m[1]] = m[2].trim().replace(/\s+/g, ' ');
  return o;
};
const todayDark = pairs(block);
// The tokens the app already had; Wind grey dark keeps today's value for each.
const EXISTING = ['bg', 'side', 'line', 'line2', 'outline', 'rowline', 'hover', 'card', 'chip', 'chipb', 'cardb', 'cshadow',
  'fg', 'fg2', 'fg3', 'glyph', 'track', 'accent', 'onaccent', 'pill', 'pillb', 'shadow', 'prog',
  'hlDim', 'hlGrey', 'fill', 'thumb', 'ctl', 'band', 'bandimg-op'];

// Edges and outlines sit closer to the card than the palette says (field report 2026-10-02, #320), in every theme
// except High contrast. Wind grey's edges come from tokens.css, which already holds the softened values.
// Per theme (owner decision, round 2): Ember as is, the black Wind grey and Ocean more.
const FADES = { grey: 0.45, ember: 0.30, ocean: 0.45 };
const EDGES = ['chipb', 'cardb', 'line', 'line2', 'pillb'];
module.exports = { FADES, EDGES };
const isHex = (v) => /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.test(v);
const rgb = (h) => { h = h.slice(1); if (h.length === 3) h = h.split('').map((c) => c + c).join(''); return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)); };
const fade = (edge, surface, k) => '#' + rgb(edge).map((v, i) => Math.round(v * (1 - k) + rgb(surface)[i] * k).toString(16).padStart(2, '0')).join('');
function map(k, radii) {
  return {
    bg: k.bg, side: k.side, line: k.line, line2: k.line2, outline: k.hb, rowline: k.rowline, hover: k.hover,
    card: k.card, chip: k.chip, chipb: k.chipb, cardb: k.cardb, cshadow: 'none',
    fg: k.fg, fg2: k.fg2, fg3: k.fg3, glyph: k.glyph, track: k.track, accent: k.pbg, onaccent: k.pfg,
    pill: k.pill, pillb: k.pillb, shadow: k.shadow, prog: k.fg,
    hlDim: k.track, hlGrey: k.sel, fill: k.fill, thumb: k.pbg, ctl: k.knob,
    band: k.bnbg, 'bandimg-op': k.bnop,
    sel: k.sel, selfg: k.selfg, onfill: k.accenton, fillline: k.fillline, focus: k.focus, hover2: k.hover2,
    danger: k.danger, dangerbg: k.dangerbg, dangerbtn: k.dangerbtn, dangerbtnfg: k.dangerbtnfg, scrim: k.scrim,
    bnfilter: k.bnfilter, bntint: k.bntint, bntop: k.bntop,
    rad: radii.rk, srad: radii.rs, rc: radii.rc, rp: radii.rp, rsw: radii.rsw, rkn: radii.rkn,
  };
}

let css = '/* GENERATED by ui/tools/gen-themes.cjs from the mockup palettes (palettes08/-b1/-b2.cjs). Do not edit by hand.\n'
  + '   One block per theme: .wnd[data-palette]. data-palette is uiPalette (global); dark only. Same token names as tokens.css plus the extra tokens listed in the generator header. */\n';
const meta = [];
for (const [id, mid] of ORDER) {
  const p = all[mid];
  if (!p) throw new Error('missing palette ' + mid);
  meta.push({ id, label: p.label });
  {
    const t = map(p.dark, p.radii);
    if (id === 'grey') for (const n of EXISTING) if (n in todayDark) t[n] = todayDark[n];
    if (id === 'grey') t.onfill = '#04201b';   // today's toggle knob colour
    // The selection is what the app already drew (--hlGrey) in Wind grey, with its text colour.
    if (id === 'grey') { t.sel = t.hlGrey; t.selfg = t.fg; }
    if (id !== 'hicon' && id !== 'grey') for (const n of EDGES) if (isHex(t[n]) && isHex(t.card)) t[n] = fade(t[n], t.card, FADES[id]);
    const lines = Object.entries(t).map(([n, v]) => `  --${n}: ${v};`);
    css += `.wnd[data-palette="${id}"] {\n${lines.join('\n')}\n  color-scheme: dark;\n}\n`;
  }
}
fs.writeFileSync(path.join(__dirname, '../src/design/themes.css'), css);

const js = "// GENERATED by ui/tools/gen-themes.cjs. The built-in themes in picker order; ids match the core's kUiPalettes.\n"
  + 'export const themes = [\n' + meta.map((m) => `  { id: '${m.id}', label: '${m.label}' },`).join('\n') + '\n];\n'
  + 'export const themeIds = themes.map((t) => t.id);\n'
  + "export const normalizePalette = (v) => (themeIds.includes(v) ? v : 'grey');\n";
fs.writeFileSync(path.join(__dirname, '../src/design/themes.js'), js);
console.log('themes.css', css.length, 'bytes;', meta.length, 'themes');
